### ISSUE TITLE
Assumes the localhost name with PC name

### ISSUE THREAD

**Issue by MusaabKh** [WolfgangFahl/pymediawikidocker#17]
While using WSL the localhost link is not the same as the PC name hence causing every redirect to go to an invalid link. The localhost link generation should not be dependent on the PC name

**Comment by WolfgangFahl** [comment]
see https://superuser.com/questions/1131874/how-to-access-localhost-of-linux-subsystem-from-windows - it looks like the WSL implementation is trying to sandbox the environment which is IMHO not a good idea since it's not transparent. So i assume you'd like a feature where you could specify the hostname being used to work around the WSL restrictions?

**Comment by WolfgangFahl** [comment]
Could you please provide an example for the invalid hostname? Did you try adding the entry manually in the 
/etc/hosts file? The /etc/host file is hiddent at 
```
%windir%\system32\drivers\etc
```
in Windows 10 and you need admin rights to edit it. Any entry such as:

```
127.0.0.1  yourhostname
```
might work around your problem.

**Comment by WolfgangFahl** [comment]
closing assuming the work around works
